### ISSUE TITLE
Improve nginx configuration template

### ISSUE THREAD

**Issue by paddycarey** [rehabstudio/oneill#20]
The nginx configuration used could probably be improved.

We need to ensure we're following SSL/TLS best practice and that any safe optimisations we can use are enabled.

It may also be worth looking into third party modules like google's pagespeed to see if we can make that work in a generic way for any arbitrary container (there are probably *some* options we can safely enable).

**Comment by pemcconnell** [comment]
I've an ansible config ready to go for pagespeed - ill review and implement this week

**Comment by paddycarey** [comment]
Closing this issue as it's no longer relevant. Feel free to submit a new nginx service container with your modifications though :)
